/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frameak;

import exekutagarriak.PartidaKudeatu;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import model.Demarcacion;
import model.Futbolista;
import model.IntegranteSeleccion;

/**
 *
 * @author soto.aitzol
 */
public class JokatutakoPartidak extends javax.swing.JFrame {

    /**
     * Creates new form JokatutakoPartidak
     */
    public JokatutakoPartidak() {
        initComponents();
        jTextAreaDatak.setEditable(false);
        jTextAreaAurkariak.setEditable(false);
        jTextAreaTxartelak.setEditable(false);
        this.setResizable(false);
        PartidaKudeatu.partidakAsmatu();
        PartidaKudeatu.selekzioOsoaSortu();
        datuakEguneratu();
        resetLista();
        comboBoxBete();
    }

    private void resetLista() {
        IntegranteSeleccion futbolaria;
        DefaultListModel listJokalariak = new DefaultListModel();
        for (int i = 0; i < PartidaKudeatu.selekzioa.size(); i++) {
            futbolaria = PartidaKudeatu.selekzioa.get(i);
            if (futbolaria instanceof Futbolista && i < 9) {
                listJokalariak.addElement("0" + futbolaria.getId() + ", " + futbolaria.getNombre());
            } else {
                listJokalariak.addElement(futbolaria.getId() + ", " + futbolaria.getNombre());
            }
        }
        jListJokalariak.setModel(listJokalariak);

        DefaultListModel listTxartelak = new DefaultListModel();
        jListTxartelak.setModel(listTxartelak);
    }

    private void datuakEguneratu() {
        String datakStr = "";
        String aurkariakStr = "";
        String txartelakStr = "";
        for (int i = 0; i < PartidaKudeatu.partidak.length; i++) {
            if (PartidaKudeatu.partidak[i] != null) {
                if (i == 0) {
                    jTextAreaDatak.setText("" + PartidaKudeatu.partidak[i].getData());
                    jTextAreaAurkariak.setText(PartidaKudeatu.partidak[i].getAurkaria());
                } else {
                    datakStr = jTextAreaDatak.getText();
                    aurkariakStr = jTextAreaAurkariak.getText();
                    jTextAreaDatak.setText(datakStr + "\n" + PartidaKudeatu.partidak[i].getData());
                    jTextAreaAurkariak.setText(aurkariakStr + "\n" + PartidaKudeatu.partidak[i].getAurkaria());
                }

            }
        }

        for (int i = 0; i < PartidaKudeatu.selekzioa.size(); i++) {
            if (i == 0 && PartidaKudeatu.txartelakIkusiFrame(i) != null) {
                jTextAreaTxartelak.setText(PartidaKudeatu.txartelakIkusiFrame(i));
            } else if (i != 0 && PartidaKudeatu.txartelakIkusiFrame(i) != null) {
                txartelakStr = jTextAreaTxartelak.getText();
                jTextAreaTxartelak.setText(txartelakStr + "\n" + PartidaKudeatu.txartelakIkusiFrame(i));
            }
        }
    }

    private void comboBoxBete() {
        //Urtea
        for (int i = 2022; i >= 1990; i--) {
            jComboBoxUrtea.addItem(String.valueOf(i));
        }
        //Hilabetea
        for (int i = 1; i <= 12; i++) {
            if (i < 10) {
                jComboBoxHilabetea.addItem("0" + String.valueOf(i));
            } else {
                jComboBoxHilabetea.addItem(String.valueOf(i));
            }

        }
        //Eguna
        for (int i = 1; i <= 31; i++) {
            if (i < 10) {
                jComboBoxEguna.addItem("0" + String.valueOf(i));
            } else {
                jComboBoxEguna.addItem(String.valueOf(i));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDatak = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAurkariak = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaTxartelak = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAurkariaSartu = new javax.swing.JTextField();
        jButtonPartidaJokatu = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListJokalariak = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListTxartelak = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jButtonGehitu = new javax.swing.JButton();
        jButtonKendu = new javax.swing.JButton();
        jComboBoxUrtea = new javax.swing.JComboBox<>();
        jComboBoxHilabetea = new javax.swing.JComboBox<>();
        jComboBoxEguna = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setFont(new java.awt.Font("Gill Sans MT", 0, 11)); // NOI18N

        jTextAreaDatak.setColumns(20);
        jTextAreaDatak.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDatak);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA (URTEA,HILABETEA,EGUNA)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATAK");

        jScrollPane2.setFont(new java.awt.Font("Gill Sans MT", 0, 11)); // NOI18N

        jTextAreaAurkariak.setColumns(20);
        jTextAreaAurkariak.setRows(5);
        jScrollPane2.setViewportView(jTextAreaAurkariak);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TXARTELAK");

        jScrollPane3.setFont(new java.awt.Font("Gill Sans MT", 0, 11)); // NOI18N

        jTextAreaTxartelak.setColumns(20);
        jTextAreaTxartelak.setRows(5);
        jScrollPane3.setViewportView(jTextAreaTxartelak);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("JOKATUTAKO PARTIDAK");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PARTIDA BERRIA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("AURKARIAK");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("AURKARIA");

        jButtonPartidaJokatu.setText("JOKATU");
        jButtonPartidaJokatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPartidaJokatuActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TXARTELAK");

        jScrollPane4.setViewportView(jListJokalariak);

        jScrollPane5.setViewportView(jListTxartelak);

        jLabel9.setText("JOKALARIAK");

        jLabel50.setText("ATERATAKO TXARTELAK");

        jButtonGehitu.setText(">");
        jButtonGehitu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGehituActionPerformed(evt);
            }
        });

        jButtonKendu.setText("<");
        jButtonKendu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKenduActionPerformed(evt);
            }
        });

        jComboBoxUrtea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUrteaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldAurkariaSartu, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jComboBoxUrtea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(jComboBoxHilabetea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(jComboBoxEguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jButtonPartidaJokatu)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(54, 54, 54))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonGehitu, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonKendu, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxUrtea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxHilabetea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxEguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAurkariaSartu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonGehitu)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonKendu)
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jButtonPartidaJokatu)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPartidaJokatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPartidaJokatuActionPerformed
        // TODO add your handling code here:
        String urtea = jComboBoxUrtea.getSelectedItem().toString();
        String hilabetea = jComboBoxHilabetea.getSelectedItem().toString();
        String eguna = jComboBoxEguna.getSelectedItem().toString();
        String aurkaria = jTextFieldAurkariaSartu.getText();
        ArrayList<Futbolista> txartelak = new ArrayList();

        //Txartelak gorde 
        for (int i = 0; i < jListTxartelak.getModel().getSize(); i++) {
            String futbolariarenDatuak = jListTxartelak.getModel().getElementAt(i);
            txartelak.add(new Futbolista(Integer.parseInt(futbolariarenDatuak.substring(0, 2)), futbolariarenDatuak.substring(4), null, 0, 0, null));
        }
        
        //Partida jokatu
        if (!urtea.equals("") && !hilabetea.equals("") && !eguna.equals("") && !aurkaria.equals("")) {
            PartidaKudeatu.partidaJokatu(urtea, hilabetea, eguna, aurkaria, txartelak);
            datuakEguneratu();
            jComboBoxUrtea.setSelectedIndex(0);
            jComboBoxHilabetea.setSelectedIndex(0);
            jComboBoxEguna.setSelectedIndex(0);
            jTextFieldAurkariaSartu.setText("");
            resetLista();
        } else {
            resetLista();
            System.out.println("Datuak falta dira");
        }
    }//GEN-LAST:event_jButtonPartidaJokatuActionPerformed

    private void jButtonGehituActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGehituActionPerformed
        // TODO add your handling code here:
        //Jokalaria txartelen listan sartu
        DefaultListModel listaTxartelak = new DefaultListModel();
        for (int i = 0; i < jListTxartelak.getModel().getSize(); i++) {
            listaTxartelak.addElement(jListTxartelak.getModel().getElementAt(i));
        }
        listaTxartelak.addElement(jListJokalariak.getSelectedValue());
        jListTxartelak.setModel(listaTxartelak);

        //Jokalaria jokalarien listatik kendu
        DefaultListModel listaJokalariak = new DefaultListModel();
        for (int i = 0; i < jListJokalariak.getModel().getSize(); i++) {
            listaJokalariak.addElement(jListJokalariak.getModel().getElementAt(i));
        }
        listaJokalariak.remove(jListJokalariak.getSelectedIndex());
        jListJokalariak.setModel(listaJokalariak);
    }//GEN-LAST:event_jButtonGehituActionPerformed

    private void jButtonKenduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKenduActionPerformed
        // TODO add your handling code here:        
        //Jokalaria jokalarien listan sartu
        DefaultListModel listaJokalariak = new DefaultListModel();
        for (int i = 0; i < jListJokalariak.getModel().getSize(); i++) {
            listaJokalariak.addElement(jListJokalariak.getModel().getElementAt(i));
        }
        listaJokalariak.addElement(jListTxartelak.getSelectedValue());
        jListJokalariak.setModel(listaJokalariak);

        //Jokalaria txartelen listatik kendu
        DefaultListModel listaTxartelak = new DefaultListModel();
        for (int i = 0; i < jListTxartelak.getModel().getSize(); i++) {
            listaTxartelak.addElement(jListTxartelak.getModel().getElementAt(i));
        }
        listaTxartelak.remove(jListTxartelak.getSelectedIndex());
        jListTxartelak.setModel(listaTxartelak);
    }//GEN-LAST:event_jButtonKenduActionPerformed

    private void jComboBoxUrteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUrteaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUrteaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JokatutakoPartidak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JokatutakoPartidak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JokatutakoPartidak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JokatutakoPartidak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JokatutakoPartidak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGehitu;
    private javax.swing.JButton jButtonKendu;
    private javax.swing.JButton jButtonPartidaJokatu;
    private javax.swing.JComboBox<String> jComboBoxEguna;
    private javax.swing.JComboBox<String> jComboBoxHilabetea;
    private javax.swing.JComboBox<String> jComboBoxUrtea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListJokalariak;
    private javax.swing.JList<String> jListTxartelak;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextAreaAurkariak;
    private javax.swing.JTextArea jTextAreaDatak;
    private javax.swing.JTextArea jTextAreaTxartelak;
    private javax.swing.JTextField jTextFieldAurkariaSartu;
    // End of variables declaration//GEN-END:variables
}
