/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frameak;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.border.EmptyBorder;
import model.Kutxa;
import model.Laukizuzena;
import model.Puntua;

/**
 *
 * @author soto.aitzol
 */
public class MarraztuJFrame extends javax.swing.JFrame {
    //private Puntua p1 = new Puntua();
    //private Kutxa k1 = new Kutxa(new Puntua(),new Puntua(),0);
    /**
     * Creates new form MarraztuJFrame
     */
    public MarraztuJFrame() {
        initComponents();
        this.setResizable(false);
        jComboBoxIrudia.removeItemAt(0);
        jComboBoxIrudia.addItem("Puntua");
        jComboBoxIrudia.addItem("Laukizuzena");
        jComboBoxIrudia.addItem("Kutxa");
        jComboBoxIrudia.setSelectedIndex(0);
        
        jButtonReset.setBackground(new Color(0x2dce98));
        jButtonReset.setBorder(new EmptyBorder(5, 15, 5, 15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldAltuera = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldZabalera = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLuzera = new javax.swing.JTextField();
        jComboBoxIrudia = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jTextFieldAltuera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAltuera.setText("5");

        jLabel1.setText("ALTUERA");

        jLabel2.setText("ZABALERA");

        jTextFieldZabalera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldZabalera.setText("50");

        jLabel3.setText("LUZERA");

        jTextFieldLuzera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldLuzera.setText("40");

        jComboBoxIrudia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboBoxIrudia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIrudiaActionPerformed(evt);
            }
        });

        jLabel4.setText("IRUDIA");

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(693, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLuzera, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAltuera, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldZabalera, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxIrudia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonReset, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAltuera, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldZabalera, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldLuzera, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxIrudia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addComponent(jButtonReset)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        /*int xKoor = evt.getX();
        int yKoor = evt.getY();
        Graphics g = this.getGraphics();
        g.setColor(Color.blue);
        //g.drawString("("+xKoor+","+yKoor+")", xKoor, yKoor-10);
        //Beheko laukia
        g.drawLine(200, 200, 260, 200);
        g.drawLine(260, 200, 275, 160);
        g.drawLine(275, 160, 215, 160);
        g.drawLine(215,160, 200, 200);
        //Altuera
        g.drawLine(200, 200, 200, 150);
        g.drawLine(260, 200, 260, 150);
        g.drawLine(275, 160, 275, 120);
        g.drawLine(215,160, 215, 120);
        //Goiko laukia
        g.drawLine(200, 150, 260, 150);
        g.drawLine(260, 150, 275, 120);
        g.drawLine(275, 120, 215, 120);
        g.drawLine(215, 120, 200, 150);*/
        int xKoor = evt.getX();
        int yKoor = evt.getY();
        int altuera = Integer.parseInt(jTextFieldAltuera.getText());
        int zabalera = Integer.parseInt(jTextFieldZabalera.getText());
        int luzera = Integer.parseInt(jTextFieldLuzera.getText());
        Graphics g = this.getGraphics();
       
        if(jComboBoxIrudia.getSelectedIndex() == 0){
            Puntua p1 = new Puntua(xKoor,yKoor);
            p1.marraztu(g);
        }else if(jComboBoxIrudia.getSelectedIndex() == 1){
            Laukizuzena l1 = new Laukizuzena(new Puntua(xKoor, yKoor), new Puntua(xKoor + zabalera, yKoor +luzera));
            l1.marraztu(g);
        }
        else if (jComboBoxIrudia.getSelectedIndex() == 2) {
            Kutxa k1 = new Kutxa(new Puntua(xKoor, yKoor), new Puntua(xKoor + zabalera, yKoor-luzera), altuera);
            k1.marraztu(g);
        }
    }//GEN-LAST:event_formMouseClicked

    private void jComboBoxIrudiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIrudiaActionPerformed
        // TODO add your handling code here:
        if(jComboBoxIrudia.getSelectedIndex() == 0){
            jTextFieldAltuera.setEnabled(false);
            jTextFieldZabalera.setEnabled(false);
            jTextFieldLuzera.setEnabled(false);
        }else if (jComboBoxIrudia.getSelectedIndex() == 1){
            jTextFieldAltuera.setEnabled(false);
            jTextFieldZabalera.setEnabled(true);
            jTextFieldLuzera.setEnabled(true);
        }else if (jComboBoxIrudia.getSelectedIndex() == 2){
            jTextFieldAltuera.setEnabled(true);
            jTextFieldZabalera.setEnabled(true);
            jTextFieldLuzera.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBoxIrudiaActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        repaint();
    }//GEN-LAST:event_jButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarraztuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarraztuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarraztuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarraztuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarraztuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboBoxIrudia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldAltuera;
    private javax.swing.JTextField jTextFieldLuzera;
    private javax.swing.JTextField jTextFieldZabalera;
    // End of variables declaration//GEN-END:variables
}
